name: Python Script CI

on:
  push:
    branches: [ "main" ]

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install flake8 (optional linter)
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 *.py

      - name: Run Python scripts
        run: |
          python bubble.py
          python test_sort.py
